//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ui.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap competitionIcon {
            get {
                object obj = ResourceManager.GetObject("competitionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atletas inscritos.
        /// </summary>
        public static string TileAthletes {
            get {
                return ResourceManager.GetString("TileAthletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competiciones activas.
        /// </summary>
        public static string TileCompetition {
            get {
                return ResourceManager.GetString("TileCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string TileTimes {
            get {
                return ResourceManager.GetString("TileTimes", resourceCulture);
            }
        }

        public static string TileCompetitionFinish {
            get {
                return ResourceManager.GetString("TileCompetitionFinish", resourceCulture);
            }
        }

         /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Competition_Id {
            get {
                return ResourceManager.GetString("Competition_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KM.
        /// </summary>
        public static string Competition_Km {
            get {
                return ResourceManager.GetString("Competition_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Competition_Name {
            get {
                return ResourceManager.GetString("Competition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de plazas.
        /// </summary>
        public static string Competition_Number {
            get {
                return ResourceManager.GetString("Competition_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio inscripción.
        /// </summary>
        public static string Competition_Price {
            get {
                return ResourceManager.GetString("Competition_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Competition_Status {
            get {
                return ResourceManager.GetString("Competition_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Competition_Date {
            get {
                return ResourceManager.GetString("Competition_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Competition_Type {
            get {
                return ResourceManager.GetString("Competition_Type", resourceCulture);
            }
        }
    }
}
