//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Main.Properties {
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ui.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Sorteo plazas.
        /// </summary>
        public static string Raffle
        {
            get
            {
                return ResourceManager.GetString("Raffle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Área Personal.
        /// </summary>
        public static string PersonalMenu {
            get {
                return ResourceManager.GetString("PersonalMenu", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Competición.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción hasta.
        /// </summary>
        public static string InscriptionClose {
            get {
                return ResourceManager.GetString("InscriptionClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción desde.
        /// </summary>
        public static string InscriptionOpen {
            get {
                return ResourceManager.GetString("InscriptionOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inscripciones registradas.
        /// </summary>
        public static string InscriptionsRegistered {
            get {
                return ResourceManager.GetString("InscriptionsRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca su dni.
        /// </summary>
        public static string InsertDni {
            get {
                return ResourceManager.GetString("InsertDni", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El atleta no está registrado en ninguna competición..
        /// </summary>
        public static string NoRegistrado {
            get {
                return ResourceManager.GetString("NoRegistrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ApplicationIco {
            get {
                object obj = ResourceManager.GetObject("ApplicationIco", resourceCulture);
                return ((System.Drawing.Bitmap) (obj));
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AthleteDni {
            get {
                return ResourceManager.GetString("AthleteDni", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AthleteDorsal {
            get {
                return ResourceManager.GetString("AthleteDorsal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AthleteGender {
            get {
                return ResourceManager.GetString("AthleteGender", resourceCulture);
            }
        }



        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AthleteName {
            get {
                return ResourceManager.GetString("AthleteName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AthleteSurname {
            get {
                return ResourceManager.GetString("AthleteSurname", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap athleticIco {
            get {
                object obj = ResourceManager.GetObject("athleticIco", resourceCulture);
                return ((System.Drawing.Bitmap) (obj));
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Competition_Date {
            get {
                return ResourceManager.GetString("Competition_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Competition_Id {
            get {
                return ResourceManager.GetString("Competition_Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a KM.
        /// </summary>
        public static string Competition_Km {
            get {
                return ResourceManager.GetString("Competition_Km", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Competition_Name {
            get {
                return ResourceManager.GetString("Competition_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Número de plazas.
        /// </summary>
        public static string Competition_Number {
            get {
                return ResourceManager.GetString("Competition_Number", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Precio inscripción.
        /// </summary>
        public static string Competition_Price {
            get {
                return ResourceManager.GetString("Competition_Price", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Competition_Status {
            get {
                return ResourceManager.GetString("Competition_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Competition_Type {
            get {
                return ResourceManager.GetString("Competition_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap competitionFinishIco {
            get {
                object obj = ResourceManager.GetObject("competitionFinishIco", resourceCulture);
                return ((System.Drawing.Bitmap) (obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap competitionIcon {
            get {
                object obj = ResourceManager.GetObject("competitionIcon", resourceCulture);
                return ((System.Drawing.Bitmap) (obj));
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Femenina.
        /// </summary>
        public static string FemaleText {
            get {
                return ResourceManager.GetString("FemaleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Masculina.
        /// </summary>
        public static string MaleText {
            get {
                return ResourceManager.GetString("MaleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Atletas inscritos.
        /// </summary>
        public static string TileAthletes {
            get {
                return ResourceManager.GetString("TileAthletes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Competiciones activas.
        /// </summary>
        public static string TileCompetition {
            get {
                return ResourceManager.GetString("TileCompetition", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Competiciones finalizadas.
        /// </summary>
        public static string TileCompetitionFinish {
            get {
                return ResourceManager.GetString("TileCompetitionFinish", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Corredores.
        /// </summary>
        public static string TitleTimesCompetition {
            get {
                return ResourceManager.GetString("TitleTimesCompetition", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo inicial (s).
        /// </summary>
        public static string InitialTime {
            get {
                return ResourceManager.GetString("InitialTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo final (s).
        /// </summary>
        public static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Añadir competidores a la carrera.
        /// </summary>
        public static string TileJoinCompetition {
            get {
                return ResourceManager.GetString("TileJoinCompetition", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BtSearch {
            get {
                return ResourceManager.GetString("BtSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca ID de la competición: .
        /// </summary>
        public static string LbCompetitionID {
            get {
                return ResourceManager.GetString("LbCompetitionID", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Colocar dorsales a jugadores inscritos.
        /// </summary>
        public static string BtInsertDorsals {
            get {
                return ResourceManager.GetString("BtInsertDorsals", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Dorsal.
        /// </summary>
        public static string TileInscriptionDorsal {
            get {
                return ResourceManager.GetString("TileInscriptionDorsal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción hasta.
        /// </summary>
        public static string LimitInscription {
            get {
                return ResourceManager.GetString("LimitInscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dorsalsIco {
            get {
                object obj = ResourceManager.GetObject("dorsalsIco", resourceCulture);
                return ((System.Drawing.Bitmap) (obj));
            }
        }

        public static string AthleteBirthDate {
            get {
                return ResourceManager.GetString("AthleteBirthDate", resourceCulture);
            }
        }

        public static string TileAthleteInscription {
            get {
                return ResourceManager.GetString("TileAthleteInscription", resourceCulture);
            }
        }

        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        public static string Competition_Inscritos {
            get {
                return ResourceManager.GetString("Competition_Inscritos", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Activas.
        /// </summary>
        public static string CategoryMenuActive {
            get {
                return ResourceManager.GetString("CategoryMenuActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Finalizadas.
        /// </summary>
        public static string CategoryMenuFinish {
            get {
                return ResourceManager.GetString("CategoryMenuFinish", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempos.
        /// </summary>
        public static string TileTimes {
            get {
                return ResourceManager.GetString("TileTimes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Competiciones activas.
        /// </summary>
        public static string TileCompetitionActive {
            get {
                return ResourceManager.GetString("TileCompetitionActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Listar atletas.
        /// </summary>
        public static string AthleteMenuList {
            get {
                return ResourceManager.GetString("AthleteMenuList", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inscribir atletas.
        /// </summary>
        public static string TileAthletesInscription {
            get {
                return ResourceManager.GetString("TileAthletesInscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AñadirDorsal.
        /// </summary>
        public static string SubmenuAddDorsal {
            get {
                return ResourceManager.GetString("SubmenuAddDorsal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Dorsal.
        /// </summary>
        public static string TileDorsal {
            get {
                return ResourceManager.GetString("TileDorsal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inscripción.
        /// </summary>
        public static string InscriptionDate {
            get {
                return ResourceManager.GetString("InscriptionDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar una competición.
        /// </summary>
        public static string TitleSelectCompetition {
            get {
                return ResourceManager.GetString("TitleSelectCompetition", resourceCulture);
            }
        }

        public static string IncompleteFields {
            get {
                return ResourceManager.GetString("IncompleteFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar inscripción.
        /// </summary>
        public static string FinishInscription {
            get {
                return ResourceManager.GetString("FinishInscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No hay una competición seleccionada..
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap default_profile {
            get {
                object obj = ResourceManager.GetObject("default_profile", resourceCulture);
                return ((System.Drawing.Bitmap) (obj));
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string TileAthletesInscriptionCompetition {
            get {
                return ResourceManager.GetString("TileAthletesInscriptionCompetition", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string AthletePosition {
            get {
                return ResourceManager.GetString("AthletePosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Justificante de inscripción.
        /// </summary>
        public static string InscriptionProof {
            get {
                return ResourceManager.GetString("InscriptionProof", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ya se inscribió anteriormente en esta competición..
        /// </summary>
        public static string PreviouslyEnrolled {
            get {
                return ResourceManager.GetString("PreviouslyEnrolled", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inscribit atleta.
        /// </summary>
        public static string MenuAthletesInscription {
            get {
                return ResourceManager.GetString("MenuAthletesInscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Mujer.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Hombre.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La edad mínima de inscripción es de 18 años..
        /// </summary>
        public static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no está pre/inscrito a ninguna competición..
        /// </summary>
        public static string NoRegistered {
            get {
                return ResourceManager.GetString("NoRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El DNI introducido no es válido..
        /// </summary>
        public static string InvalidDNI {
            get {
                return ResourceManager.GetString("InvalidDNI", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar método de pago.
        /// </summary>
        public static string PaymentMethodSelection {
            get {
                return ResourceManager.GetString("PaymentMethodSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia bancaria.
        /// </summary>
        public static string WireTransfer {
            get {
                return ResourceManager.GetString("WireTransfer", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Datos del beneficiario: Gestor de carreras populares.
        /// </summary>
        public static string BeneficiaryData {
            get {
                return ResourceManager.GetString("BeneficiaryData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a IBAN: ES11 2222 3333 4444 5555 6666.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad a abonar:.
        /// </summary>
        public static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Dispone de 48h para realizar la transferencia..
        /// </summary>
        public static string PaymentTimeLimit {
            get {
                return ResourceManager.GetString("PaymentTimeLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Datos para la transferencia.
        /// </summary>
        public static string TransferData {
            get {
                return ResourceManager.GetString("TransferData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Absoluta.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar inscripciones.
        /// </summary>
        public static string FinishInscriptions {
            get {
                return ResourceManager.GetString("FinishInscriptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar extracto bancario.
        /// </summary>
        public static string DocumentSelection {
            get {
                return ResourceManager.GetString("DocumentSelection", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        public static string TilePayments {
            get {
                return ResourceManager.GetString("TilePayments", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Comprobar pagos de inscripción.
        /// </summary>
        public static string TitleFinishPayment {
            get {
                return ResourceManager.GetString("TitleFinishPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar estado de las inscripciones.
        /// </summary>
        public static string UpdateInscriptionsState {
            get {
                return ResourceManager.GetString("UpdateInscriptionsState", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado ningún extracto bancario..
        /// </summary>
        public static string NotSelectedFile {
            get {
                return ResourceManager.GetString("NotSelectedFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El extracto seleccionado está vacío..
        /// </summary>
        public static string EmptyDocument {
            get {
                return ResourceManager.GetString("EmptyDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El documento seleccionado no es válido..
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a D+.
        /// </summary>
        public static string PositiveDesnivel {
            get {
                return ResourceManager.GetString("PositiveDesnivel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Categorías predefinidas.
        /// </summary>
        public static string Predefined {
            get {
                return ResourceManager.GetString("Predefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nueva .
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a D-.
        /// </summary>
        public static string NegativeDesnivel {
            get {
                return ResourceManager.GetString("NegativeDesnivel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Desnivel.
        /// </summary>
        public static string Desnivel {
            get {
                return ResourceManager.GetString("Desnivel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Reglamento.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el pdf del reglamento....
        /// </summary>
        public static string FileSelect {
            get {
                return ResourceManager.GetString("FileSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Configurador de carreras.
        /// </summary>
        public static string TitleConfigureCompetition {
            get {
                return ResourceManager.GetString("TitleConfigureCompetition", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Montaña.
        /// </summary>
        public static string Mountain {
            get {
                return ResourceManager.GetString("Mountain", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Asfalto.
        /// </summary>
        public static string Asfalto {
            get {
                return ResourceManager.GetString("Asfalto", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la competición.
        /// </summary>
        public static string CompetitionName {
            get {
                return ResourceManager.GetString("CompetitionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar inscripción.
        /// </summary>
        public static string CancelInscription {
            get {
                return ResourceManager.GetString("CancelInscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Devolución.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Final del plazo de cancelación.
        /// </summary>
        public static string CancelFinishDate {
            get {
                return ResourceManager.GetString("CancelFinishDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inicio del plazo de cancelación.
        /// </summary>
        public static string CancelInitialDate {
            get {
                return ResourceManager.GetString("CancelInitialDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Hito nº.
        /// </summary>
        public static string MilestoneNumber {
            get {
                return ResourceManager.GetString("MilestoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempos parciales.
        /// </summary>
        public static string SubMenuPartialTimes {
            get {
                return ResourceManager.GetString("SubMenuPartialTimes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Insertar tiempos.
        /// </summary>
        public static string TitleAddPartialTimes {
            get {
                return ResourceManager.GetString("TitleAddPartialTimes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Insertar tiempos.
        /// </summary>
        public static string DocumentSelectionTime {
            get {
                return ResourceManager.GetString("DocumentSelectionTime", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cancelado la inscripción..
        /// </summary>
        public static string InscriptionCanceled {
            get {
                return ResourceManager.GetString("InscriptionCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ver todas las clasificaciones.
        /// </summary>
        public static string GetCompetitionsTimes {
            get {
                return ResourceManager.GetString("GetCompetitionsTimes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo por minuto.
        /// </summary>
        public static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta de crédito (Visa, MasterCard, Maestro).
        /// </summary>
        public static string CreditCard
        {
            get
            {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Número de tarjeta:.
        /// </summary>
        public static string CardNumber
        {
            get
            {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cvc:.
        /// </summary>
        public static string Cvc
        {
            get
            {
                return ResourceManager.GetString("Cvc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Caducidad:.
        /// </summary>
        public static string Expiration
        {
            get
            {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El número de tarjeta no es correcto.
        /// </summary>
        public static string InvalidNumber
        {
            get
            {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La tarjeta ha caducado.
        /// </summary>
        public static string ExpiredCard
        {
            get
            {
                return ResourceManager.GetString("ExpiredCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cvc incorrecto.
        /// </summary>
        public static string IncorrectCvc
        {
            get
            {
                return ResourceManager.GetString("IncorrectCvc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El formato de fecha es incorrecto. Debe ser &apos;mm/yy&apos;.
        /// </summary>
        public static string InvalidDate
        {
            get
            {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
    }
}
